sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.0.1 - Add columns in Operador.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.0.2 - Alter columns in StockHistorico.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.0.3 - Add new UserRole.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.0.4 - Alter null columns.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.0.5 - Update UserRole.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.0.6 - Update JerarquiaUsuarios.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.0.7 - Add column in Maquina.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.0.8 - Create table ArticuloAsignacion.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.0.9 - Drop table ArticuloMaquina.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.1.0 - Add UnidadMedida in Articulo.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.1.1- Add OperadorID in Articulo.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.1.2- Drop columns in Articulo.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.1.3- Add columns in ArticuloAsignacion.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.1.4- Drop columns in Stock.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.1.5- Alter columns in Stock and ArticuloAsignacion.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.1.6- Trigger on Transaction Creation.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.1.7- Security Tables.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.1.8- Permissions.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.1.9- Create CargaInformeTransacciones SP.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.2.0- Create CargaInformeEntregaEPP SP.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.2.1- Update and Insert in Funcion.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.2.2- Add Column in Maquina.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.2.3- Update and Insert in Funcion.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.2.4- Add Column AspNetRoles.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.2.5- Add Column StockHistorico.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.2.6- Create AlarmaConfiguracion.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.2.7- Alter Column Usuario.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.2.8- Update Transaccion Trigger.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.2.9- Alter CargaInformeTransacciones SP.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.3.0- Alter CargaInformeEntregaEPP SP.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.0.3.1- Add new Permissions.sql"
