sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.1 - Reemplazar Periodo Quincenal por Semanal.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.2 - Alter column Maquina.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.3 - Alter CargaInformeTransacciones SP.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.4 - Add column in Usuario.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.5 - Add column in Maquina.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.6 - Add new UserRole.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.7 - Rename column Transaccion.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.8 - Create table FuncionOperador.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.9 - Alter table Funcion.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.10 - Add new Permissions.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.11 - Update Permissions.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.12 - Add column in Operador.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.13 - Update Descripcion in TipoDeAlarma.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.14 - Create function Split.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.15 - Alter procedure CargaInformeEntregaTotalEPP.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.16 - Update Weight in AspNetRoles.sql"
sqlcmd -S %1 -d %2 -W -i "Bugs 1.3.1.17 - Add new Permission.sql"